; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.word $0000	; Alternate level layout
	.word $0000	; Alternate object layout
	.byte LEVEL1_SIZE_10 | LEVEL1_YSTART_140
	.byte LEVEL2_BGPAL_04 | LEVEL2_OBJPAL_09 | LEVEL2_XSTART_18
	.byte LEVEL3_TILESET_04 | LEVEL3_VSCROLL_LOCKED | LEVEL3_PIPENOTEXIT
	.byte LEVEL4_BGBANK_INDEX(2) | LEVEL4_INITACT_NOTHING
	.byte LEVEL5_BGM_CASTLE | LEVEL5_TIME_300

	.byte $E2, $51, $30, $E3, $F8, $30, $E0, $52, $20, $E4, $58, $43, $6B, $00, $3F, $9F
	.byte $77, $00, $D3, $14, $76, $00, $D4, $04, $6D, $00, $D4, $0D, $70, $0D, $D4, $00
	.byte $73, $0F, $D3, $05, $6D, $0E, $D2, $91, $6F, $16, $D7, $0F, $7A, $16, $D0, $89
	.byte $7A, $36, $40, $05, $79, $3D, $D0, $07, $78, $3E, $D0, $06, $77, $3F, $D0, $05
	.byte $76, $40, $D0, $05, $7A, $45, $40, $00, $6E, $40, $D4, $1B, $76, $47, $D0, $06
	.byte $76, $4F, $D0, $08, $7A, $4E, $40, $00, $7A, $52, $40, $00, $7A, $57, $40, $00
	.byte $76, $59, $D4, $03, $7A, $5D, $40, $02, $7A, $65, $40, $03, $7A, $6C, $40, $00
	.byte $76, $66, $D0, $01, $7A, $71, $40, $1C, $77, $75, $D3, $02, $6E, $69, $D4, $03
	.byte $77, $7A, $D3, $06, $56, $81, $4C, $76, $81, $30, $0C, $76, $8E, $D4, $02, $6F
	.byte $8F, $D3, $01, $15, $8E, $0B, $71, $49, $31, $01, $71, $4D, $31, $01, $71, $58
	.byte $31, $01, $71, $52, $31, $01, $72, $35, $D0, $00, $72, $32, $D0, $00, $70, $32
	.byte $D1, $03, $70, $62, $D0, $00, $70, $65, $D0, $00, $73, $69, $D0, $00, $73, $6C
	.byte $D0, $00, $FF