; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.word W4F1BL	; Alternate level layout
	.word W4F1BO	; Alternate object layout
	.byte LEVEL1_SIZE_14 | LEVEL1_YSTART_140
	.byte LEVEL2_BGPAL_04 | LEVEL2_OBJPAL_09 | LEVEL2_XSTART_18
	.byte LEVEL3_TILESET_02 | LEVEL3_VSCROLL_LOCKED | LEVEL3_PIPENOTEXIT
	.byte LEVEL4_BGBANK_INDEX(2) | LEVEL4_INITACT_NOTHING
	.byte LEVEL5_BGM_CASTLE | LEVEL5_TIME_300

	.byte $6B, $00, $3F, $E1, $E6, $68, $10, $7A, $07, $D0, $16, $76, $00, $D4, $03, $6D
	.byte $00, $D4, $2D, $36, $0F, $22, $36, $11, $00, $76, $1F, $D4, $0F, $72, $1F, $D0
	.byte $0E, $6D, $2E, $D2, $B9, $7A, $2F, $40, $2D, $70, $12, $31, $01, $36, $14, $22
	.byte $71, $26, $31, $01, $74, $33, $D0, $03, $78, $39, $D0, $03, $7A, $41, $D0, $1B
	.byte $70, $42, $D6, $0E, $6E, $34, $31, $01, $70, $39, $D0, $00, $70, $3C, $D0, $00
	.byte $73, $55, $D6, $07, $15, $52, $E0, $01, $6E, $52, $31, $01, $70, $61, $D6, $02
	.byte $7A, $61, $D0, $7E, $76, $72, $D0, $0D, $70, $64, $D0, $00, $70, $67, $D0, $00
	.byte $7A, $80, $40, $01, $33, $7E, $A2, $76, $84, $D0, $0E, $72, $85, $D0, $0C, $7A
	.byte $91, $40, $00, $73, $92, $D3, $0F, $32, $90, $0E, $32, $91, $0E, $7A, $A2, $40
	.byte $02, $77, $A5, $D3, $00, $77, $A8, $D3, $00, $39, $A6, $A1, $6E, $82, $31, $01
	.byte $36, $91, $0E, $76, $B4, $D0, $00, $77, $BA, $D3, $01, $77, $BF, $D3, $01, $56
	.byte $C1, $4C, $76, $CE, $D4, $02, $70, $CF, $D2, $01, $7A, $A9, $40, $10, $7A, $BC
	.byte $40, $02, $7A, $C1, $40, $0C, $15, $CE, $0B, $76, $C1, $30, $0C, $FF