; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.word W401L	; Alternate level layout
	.word W401O	; Alternate object layout
	.byte LEVEL1_SIZE_05 | LEVEL1_YSTART_170
	.byte LEVEL2_BGPAL_00 | LEVEL2_OBJPAL_08 | LEVEL2_XSTART_18
	.byte LEVEL3_TILESET_01 | LEVEL3_VSCROLL_LOCKED | LEVEL3_PIPENOTEXIT
	.byte LEVEL4_BGBANK_INDEX(6) | LEVEL4_INITACT_NOTHING
	.byte LEVEL5_BGM_UNDERWATER | LEVEL5_TIME_300

	.byte $00, $00, $0D, $7A, $00, $50, $3F, $17, $07, $E2, $14, $0B, $E5, $39, $0D, $4F
	.byte $38, $0E, $4F, $37, $0F, $4F, $36, $10, $4F, $39, $1D, $42, $38, $1E, $41, $37
	.byte $1F, $40, $32, $10, $4F, $31, $10, $4F, $30, $10, $4F, $2F, $10, $4F, $6E, $00
	.byte $50, $55, $39, $20, $8F, $35, $23, $89, $31, $26, $83, $2F, $30, $4F, $30, $30
	.byte $4F, $31, $30, $4F, $39, $30, $4F, $38, $30, $4F, $37, $30, $4F, $35, $33, $89
	.byte $14, $46, $E5, $16, $49, $E2, $39, $49, $4F, $38, $4A, $4F, $37, $4B, $4F, $36
	.byte $4C, $4F, $34, $4E, $EF, $6E, $4E, $55, $4F, $7A, $45, $50, $3F, $E4, $71, $0A
	.byte $2F, $02, $D1, $FF