; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.word W101BL	; Alternate level layout
	.word W101BO	; Alternate object layout
	.byte LEVEL1_SIZE_12 | LEVEL1_MUCK | LEVEL1_YSTART_180
	.byte LEVEL2_BGPAL_04 | LEVEL2_OBJPAL_08 | LEVEL2_XSTART_18
	.byte LEVEL3_TILESET_01 | LEVEL3_VSCROLL_LOCKED | LEVEL3_PIPENOTEXIT
	.byte LEVEL4_BGBANK_INDEX(1) | LEVEL4_INITACT_NOTHING
	.byte LEVEL5_BGM_OVERWORLD | LEVEL5_TIME_300

	.byte $1A, $00, $C0, $BF, $10, $00, $E3, $17, $0B, $01, $19, $0F, $92, $36, $11, $45
	.byte $35, $11, $40, $34, $11, $40, $33, $11, $40, $32, $11, $40, $32, $12, $14, $35
	.byte $16, $40, $36, $12, $13, $36, $13, $06, $17, $15, $01, $36, $1A, $24, $3A, $20
	.byte $A0, $10, $12, $E2, $0F, $1B, $E2, $10, $1E, $E3, $19, $26, $93, $36, $27, $A3
	.byte $17, $29, $01, $3A, $2D, $A0, $35, $2B, $0F, $1A, $34, $A4, $10, $30, $E3, $0F
	.byte $2D, $E2, $17, $3A, $01, $19, $3E, $93, $36, $3A, $1A, $32, $38, $1D, $31, $3A
	.byte $87, $36, $47, $40, $37, $46, $41, $38, $45, $42, $1A, $4B, $A6, $36, $48, $0A
	.byte $32, $49, $13, $10, $42, $E2, $32, $4E, $1C, $39, $51, $40, $36, $55, $28, $35
	.byte $5E, $40, $36, $5E, $40, $17, $45, $90, $17, $47, $01, $39, $44, $43, $0F, $4B
	.byte $E2, $10, $4E, $E3, $0F, $5D, $E2, $17, $56, $01, $19, $54, $91, $17, $6A, $01
	.byte $19, $6E, $93, $10, $60, $E3, $17, $75, $01, $36, $7B, $A3, $10, $72, $E2, $0F
	.byte $7B, $E2, $10, $7E, $E3, $1A, $7C, $A4, $36, $80, $93, $1A, $81, $A3, $32, $7D
	.byte $15, $19, $88, $93, $17, $8C, $01, $36, $90, $A3, $36, $94, $23, $33, $95, $A2
	.byte $1A, $98, $A4, $10, $92, $E3, $0F, $8F, $E2, $17, $9C, $01, $19, $A0, $93, $38
	.byte $A4, $A1, $17, $A6, $01, $10, $A3, $E2, $0F, $AC, $E2, $10, $AF, $E3, $19, $B5
	.byte $93, $51, $BD, $09, $17, $B8, $01, $E8, $42, $10, $36, $3A, $08, $36, $97, $00
	.byte $59, $AC, $B0, $08, $58, $AD, $B0, $07, $57, $AE, $B0, $06, $56, $AF, $B0, $05
	.byte $55, $B0, $B0, $04, $54, $B1, $B0, $03, $53, $B2, $B0, $02, $52, $B3, $B0, $01
	.byte $FF