; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.word W101AL	; Alternate level layout
	.word W101AO	; Alternate object layout
	.byte LEVEL1_SIZE_01 | LEVEL1_YSTART_170
	.byte LEVEL2_BGPAL_06 | LEVEL2_OBJPAL_10 | LEVEL2_XSTART_18
	.byte LEVEL3_TILESET_01 | LEVEL3_VSCROLL_LOCKED | LEVEL3_PIPENOTEXIT
	.byte LEVEL4_BGBANK_INDEX(1) | LEVEL4_INITACT_NOTHING
	.byte LEVEL5_BGM_UNDERGROUND | LEVEL5_TIME_300

	.byte $2F, $03, $06, $38, $00, $10, $37, $00, $10, $36, $00, $10, $35, $00, $10, $34
	.byte $00, $10, $33, $00, $10, $32, $00, $10, $31, $00, $10, $30, $00, $10, $2F, $00
	.byte $10, $36, $01, $0E, $36, $03, $0E, $37, $05, $87, $39, $03, $89, $2F, $0F, $DB
	.byte $38, $0D, $E1, $39, $00, $10, $33, $04, $0E, $1A, $00, $C0, $10, $2F, $04, $1A
	.byte $0F, $01, $05, $0F, $02, $05, $E0, $71, $4A, $FF