; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.word W102BL	; Alternate level layout
	.word W102BO	; Alternate object layout
	.byte LEVEL1_SIZE_01 | LEVEL1_MUCK | LEVEL1_YSTART_180
	.byte LEVEL2_BGPAL_04 | LEVEL2_OBJPAL_08 | LEVEL2_XSTART_18
	.byte LEVEL3_TILESET_01 | LEVEL3_VSCROLL_LOCKED | LEVEL3_PIPENOTEXIT
	.byte LEVEL4_BGBANK_INDEX(1) | LEVEL4_INITACT_NOTHING
	.byte LEVEL5_BGM_OVERWORLD | LEVEL5_TIME_300

	.byte $01, $A1, $02, $38, $0A, $E1, $36, $0C, $A3, $14, $09, $E2, $10, $03, $E3, $E0
	.byte $42, $10, $1A, $00, $C0, $0F, $FF