; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.word W102DL	; Alternate level layout
	.word W102OL	; Alternate object layout
	.byte LEVEL1_SIZE_06 | LEVEL1_YSTART_170
	.byte LEVEL2_BGPAL_06 | LEVEL2_OBJPAL_10 | LEVEL2_XSTART_18
	.byte LEVEL3_TILESET_01 | LEVEL3_VSCROLL_LOCKED | LEVEL3_PIPENOTEXIT
	.byte LEVEL4_BGBANK_INDEX(1) | LEVEL4_INITACT_NOTHING
	.byte LEVEL5_BGM_UNDERGROUND | LEVEL5_TIME_300

	.byte $2E, $01, $D2, $38, $00, $10, $37, $00, $10, $36, $00, $10, $35, $00, $10, $34
	.byte $00, $10, $32, $00, $10, $31, $00, $10, $33, $00, $10, $39, $00, $10, $30, $00
	.byte $10, $2F, $00, $10, $1A, $00, $C0, $5F, $36, $09, $21, $36, $0B, $00, $1A, $0B
	.byte $A9, $36, $14, $A3, $1A, $15, $A4, $36, $1A, $A3, $1A, $1B, $AD, $37, $28, $A2
	.byte $32, $16, $82, $1A, $30, $A2, $38, $30, $11, $37, $30, $11, $36, $30, $11, $35
	.byte $30, $11, $34, $30, $11, $33, $30, $11, $32, $30, $11, $31, $30, $11, $30, $30
	.byte $11, $2F, $30, $11, $38, $34, $91, $1A, $3B, $A4, $39, $3F, $1F, $39, $4F, $11
	.byte $38, $4F, $11, $38, $3F, $1F, $36, $3F, $1F, $37, $3F, $1F, $35, $3F, $1F, $34
	.byte $3F, $1F, $33, $3F, $1F, $32, $3F, $1F, $31, $3F, $1F, $2F, $3F, $1F, $30, $3F
	.byte $1F, $37, $4F, $11, $35, $4F, $11, $36, $4F, $11, $34, $4F, $11, $33, $4F, $11
	.byte $32, $4F, $11, $30, $4F, $11, $2F, $4F, $1C, $2F, $4F, $11, $31, $4F, $11, $2F
	.byte $5E, $11, $30, $5E, $11, $31, $5E, $11, $32, $5E, $11, $33, $5E, $11, $34, $5E
	.byte $11, $35, $5E, $11, $36, $5E, $11, $37, $5E, $11, $38, $5E, $11, $39, $5E, $11
	.byte $36, $57, $0B, $36, $5D, $0E, $32, $5D, $0E, $36, $3B, $0E, $33, $3C, $0E, $E3
	.byte $42, $10, $FF