; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.word W102BL	; Alternate level layout
	.word W102BO	; Alternate object layout
	.byte LEVEL1_SIZE_02 | LEVEL1_YSTART_170
	.byte LEVEL2_BGPAL_06 | LEVEL2_OBJPAL_10 | LEVEL2_XSTART_18
	.byte LEVEL3_TILESET_01 | LEVEL3_VSCROLL_LOCKED | LEVEL3_PIPENOTEXIT
	.byte LEVEL4_BGBANK_INDEX(1) | LEVEL4_INITACT_NOTHING
	.byte LEVEL5_BGM_UNDERGROUND | LEVEL5_TIME_300

	.byte $2F, $10, $1F, $2F, $1F, $DB, $39, $00, $10, $38, $00, $10, $37, $00, $10, $36
	.byte $00, $10, $35, $00, $10, $34, $00, $10, $33, $00, $10, $32, $00, $10, $31, $00
	.byte $10, $30, $00, $10, $1A, $00, $C0, $1F, $2F, $00, $1F, $2F, $01, $D1, $38, $08
	.byte $10, $37, $08, $10, $36, $08, $1F, $38, $09, $8F, $36, $18, $13, $37, $19, $10
	.byte $38, $19, $10, $35, $19, $10, $34, $19, $10, $32, $19, $12, $33, $19, $10, $33
	.byte $1B, $10, $34, $1B, $10, $35, $1B, $10, $37, $1B, $10, $32, $1A, $0A, $59, $10
	.byte $30, $38, $1D, $E1, $E1, $71, $18, $FF