; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.word W301CL	; Alternate level layout
	.word W301CO	; Alternate object layout
	.byte LEVEL1_SIZE_02 | LEVEL1_YSTART_170
	.byte LEVEL2_BGPAL_06 | LEVEL2_OBJPAL_10 | LEVEL2_XSTART_18
	.byte LEVEL3_TILESET_01 | LEVEL3_VSCROLL_LOCKED | LEVEL3_PIPENOTEXIT
	.byte LEVEL4_BGBANK_INDEX(24) | LEVEL4_INITACT_NOTHING
	.byte LEVEL5_BGM_UNDERGROUND | LEVEL5_TIME_300

	.byte $2F, $1F, $DB, $5A, $00, $C0, $1F, $39, $00, $10, $38, $00, $10, $37, $00, $10
	.byte $36, $00, $10, $35, $00, $10, $34, $00, $10, $33, $00, $10, $32, $00, $10, $31
	.byte $00, $10, $30, $00, $10, $2F, $00, $10, $2F, $03, $1F, $2F, $13, $1B, $38, $08
	.byte $10, $37, $08, $10, $36, $08, $1F, $36, $18, $13, $38, $1D, $E1, $35, $1B, $10
	.byte $34, $1B, $10, $33, $1B, $10, $32, $19, $12, $33, $19, $10, $34, $19, $10, $35
	.byte $19, $10, $37, $19, $10, $38, $19, $10, $37, $1B, $10, $32, $1A, $0A, $38, $09
	.byte $8F, $59, $10, $30, $2F, $01, $D1, $E1, $71, $20, $FF