; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.word $0000	; Alternate level layout
	.word $0000	; Alternate object layout
	.byte LEVEL1_SIZE_02 | LEVEL1_YSTART_170
	.byte LEVEL2_BGPAL_07 | LEVEL2_OBJPAL_08 | LEVEL2_XSTART_18
	.byte LEVEL3_TILESET_00 | LEVEL3_VSCROLL_LOCKED
	.byte LEVEL4_BGBANK_INDEX(24) | LEVEL4_INITACT_NOTHING
	.byte LEVEL5_BGM_OVERWORLD | LEVEL5_TIME_300

	.byte $10, $10, $E3, $5A, $00, $C0, $0F, $4F, $1E, $CB, $01, $31, $0E, $4D, $32, $0D
	.byte $42, $33, $0C, $43, $34, $0B, $44, $35, $0A, $45, $36, $09, $46, $37, $08, $47
	.byte $38, $07, $48, $39, $06, $49, $38, $02, $A1, $17, $1A, $01, $5A, $11, $C0, $0C
	.byte $0F, $0D, $E2, $59, $05, $A0, $00, $36, $16, $20, $FF