; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.word W301L	; Alternate level layout
	.word W301O	; Alternate object layout
	.byte LEVEL1_SIZE_01 | LEVEL1_YSTART_170
	.byte LEVEL2_BGPAL_06 | LEVEL2_OBJPAL_10 | LEVEL2_XSTART_18
	.byte LEVEL3_TILESET_01 | LEVEL3_VSCROLL_LOCKED | LEVEL3_PIPENOTEXIT
	.byte LEVEL4_BGBANK_INDEX(24) | LEVEL4_INITACT_NOTHING
	.byte LEVEL5_BGM_UNDERGROUND | LEVEL5_TIME_300

	.byte $2F, $0F, $CB, $5A, $00, $C0, $02, $5A, $04, $C0, $0B, $39, $00, $10, $38, $00
	.byte $10, $37, $00, $10, $36, $00, $10, $35, $00, $10, $34, $00, $10, $33, $00, $10
	.byte $32, $00, $10, $31, $00, $10, $30, $00, $10, $2F, $00, $10, $2F, $04, $1A, $30
	.byte $04, $10, $31, $04, $10, $32, $04, $10, $33, $04, $10, $34, $04, $10, $35, $04
	.byte $10, $36, $04, $17, $37, $0B, $10, $38, $0B, $10, $38, $06, $10, $37, $06, $10
	.byte $38, $0D, $E1, $36, $0B, $0A, $35, $05, $85, $39, $07, $83, $2F, $01, $D1, $E0
	.byte $71, $35, $FF