; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.word W302BL	; Alternate level layout
	.word W302BO	; Alternate object layout
	.byte LEVEL1_SIZE_01 | LEVEL1_YSTART_180
	.byte LEVEL2_BGPAL_05 | LEVEL2_OBJPAL_08 | LEVEL2_XSTART_18
	.byte LEVEL3_TILESET_06 | LEVEL3_VSCROLL_LOCKED | LEVEL3_PIPENOTEXIT
	.byte LEVEL4_BGBANK_INDEX(24) | LEVEL4_INITACT_NOTHING
	.byte LEVEL5_BGM_UNDERWATER | LEVEL5_TIME_300

	.byte $14, $09, $E2, $11, $03, $E3, $36, $0C, $80, $37, $0D, $80, $38, $0C, $80, $37
	.byte $0B, $80, $37, $0C, $80, $36, $0E, $80, $36, $0A, $80, $35, $0C, $80, $34, $0C
	.byte $80, $33, $0C, $80, $32, $0C, $80, $E0, $42, $20, $5A, $00, $C0, $0F, $5A, $0B
	.byte $80, $02, $FF