; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.word $0000	; Alternate level layout
	.word $0000	; Alternate object layout
	.byte LEVEL1_SIZE_02 | LEVEL1_YSTART_170
	.byte LEVEL2_BGPAL_07 | LEVEL2_OBJPAL_08 | LEVEL2_XSTART_18
	.byte LEVEL3_TILESET_00 | LEVEL3_VSCROLL_LOCKLOW
	.byte LEVEL4_BGBANK_INDEX(24) | LEVEL4_INITACT_NOTHING
	.byte LEVEL5_BGM_OVERWORLD | LEVEL5_TIME_300

	.byte $5A, $00, $C0, $1F, $38, $03, $A1, $59, $00, $A0, $01, $17, $05, $01, $59, $0B
	.byte $B0, $08, $58, $0C, $B0, $07, $57, $0D, $B0, $06, $56, $0E, $B0, $05, $55, $0F
	.byte $B0, $04, $54, $10, $B0, $03, $53, $11, $B0, $02, $52, $12, $B0, $01, $17, $18
	.byte $01, $51, $1C, $09, $59, $16, $A0, $01, $10, $0E, $E3, $0F, $0B, $E2, $10, $02
	.byte $E2, $FF