; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.word W401BL	; Alternate level layout
	.word W401BO	; Alternate object layout
	.byte LEVEL1_SIZE_13 | LEVEL1_YSTART_180
	.byte LEVEL2_BGPAL_04 | LEVEL2_OBJPAL_08 | LEVEL2_XSTART_18
	.byte LEVEL3_TILESET_06 | LEVEL3_VSCROLL_LOCKED | LEVEL3_PIPENOTEXIT
	.byte LEVEL4_BGBANK_INDEX(14) | LEVEL4_INITACT_NOTHING
	.byte LEVEL5_BGM_MARIOLAND | LEVEL5_TIME_300

	.byte $1A, $00, $C0, $4A, $19, $0C, $92, $19, $10, $92, $19, $17, $90, $38, $19, $A1
	.byte $3A, $1E, $A0, $39, $22, $10, $38, $22, $10, $35, $22, $10, $36, $22, $0A, $10
	.byte $1A, $E4, $0F, $23, $E3, $31, $21, $0E, $0F, $12, $E2, $10, $08, $E2, $19, $29
	.byte $90, $39, $2A, $40, $38, $2A, $40, $37, $2A, $40, $17, $30, $01, $36, $34, $A3
	.byte $37, $3D, $25, $37, $43, $00, $19, $3B, $92, $19, $47, $90, $39, $4A, $40, $1A
	.byte $54, $C0, $3E, $39, $54, $40, $19, $58, $91, $39, $62, $46, $38, $63, $45, $37
	.byte $64, $44, $36, $65, $43, $35, $66, $42, $34, $67, $41, $33, $68, $40, $17, $5E
	.byte $01, $36, $69, $0F, $19, $6A, $92, $19, $6E, $92, $19, $3F, $92, $19, $76, $90
	.byte $39, $77, $40, $35, $7C, $A4, $36, $78, $22, $19, $87, $91, $17, $8D, $01, $35
	.byte $91, $20, $35, $92, $00, $35, $95, $25, $33, $97, $A1, $33, $99, $A1, $1A, $95
	.byte $C0, $0D, $33, $95, $91, $38, $A0, $A1, $1A, $A4, $C0, $02, $1A, $AC, $C0, $04
	.byte $1A, $B2, $C0, $10, $1A, $C4, $C0, $10, $51, $C4, $09, $59, $B3, $B0, $07, $58
	.byte $B4, $B0, $06, $57, $B5, $B0, $05, $56, $B6, $B0, $04, $55, $B7, $B0, $03, $54
	.byte $B8, $B0, $02, $53, $B9, $B0, $01, $52, $BA, $B0, $00, $17, $BE, $01, $37, $A8
	.byte $A3, $36, $AD, $A3, $36, $A4, $20, $32, $A7, $0C, $10, $C5, $E2, $19, $CE, $92
	.byte $19, $CA, $92, $0F, $B2, $E3, $10, $A8, $E4, $0F, $A0, $E2, $19, $A5, $90, $19
	.byte $9D, $92, $19, $99, $92, $10, $95, $E2, $10, $79, $E4, $0F, $82, $E3, $0F, $72
	.byte $E2, $10, $66, $E2, $0F, $53, $E3, $10, $4A, $E4, $0F, $42, $E2, $10, $37, $E2
	.byte $E9, $42, $20, $EA, $78, $40, $FF