; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.word W401L	; Alternate level layout
	.word W401O	; Alternate object layout
	.byte LEVEL1_SIZE_08 | LEVEL1_YSTART_170
	.byte LEVEL2_BGPAL_04 | LEVEL2_OBJPAL_08 | LEVEL2_XSTART_18
	.byte LEVEL3_TILESET_01 | LEVEL3_VSCROLL_LOCKED
	.byte LEVEL4_BGBANK_INDEX(1) | LEVEL4_INITACT_NOTHING
	.byte LEVEL5_BGM_SPECIAL | LEVEL5_TIME_300

	.byte $7A, $00, $3F, $7A, $10, $3F, $7A, $20, $3F, $17, $04, $06, $76, $04, $30, $32
	.byte $10, $8F, $32, $22, $8D, $31, $20, $10, $30, $20, $10, $2F, $20, $10, $32, $20
	.byte $10, $33, $20, $10, $34, $20, $10, $35, $20, $10, $36, $20, $10, $16, $30, $BF
	.byte $7A, $30, $3F, $7A, $40, $3F, $39, $32, $8C, $32, $40, $8F, $7A, $50, $34, $32
	.byte $60, $8A, $3A, $6C, $82, $E5, $48, $06, $E6, $48, $06, $E7, $48, $06, $FF