; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.word W402BL	; Alternate level layout
	.word W402BO	; Alternate object layout
	.byte LEVEL1_SIZE_13 | LEVEL1_YSTART_180
	.byte LEVEL2_BGPAL_04 | LEVEL2_OBJPAL_08 | LEVEL2_XSTART_18
	.byte LEVEL3_TILESET_14 | LEVEL3_VSCROLL_LOCKED | LEVEL3_PIPENOTEXIT
	.byte LEVEL4_BGBANK_INDEX(14) | LEVEL4_INITACT_NOTHING
	.byte LEVEL5_BGM_MARIOLAND | LEVEL5_TIME_300

	.byte $1A, $00, $C0, $2B, $19, $0C, $92, $58, $11, $31, $56, $11, $31, $59, $16, $30
	.byte $57, $16, $31, $55, $19, $34, $37, $14, $00, $19, $18, $90, $37, $1D, $08, $37
	.byte $1E, $21, $19, $29, $91, $1A, $2E, $C0, $06, $17, $2F, $01, $3A, $36, $40, $1A
	.byte $38, $C0, $46, $19, $3A, $92, $39, $3D, $40, $38, $3D, $40, $37, $3D, $40, $32
	.byte $39, $1A, $36, $42, $18, $35, $4A, $40, $36, $4A, $40, $19, $3F, $90, $19, $46
	.byte $90, $19, $58, $91, $17, $5E, $01, $19, $6A, $92, $19, $6F, $90, $35, $73, $A4
	.byte $19, $76, $90, $58, $79, $31, $36, $79, $00, $36, $7A, $27, $59, $81, $30, $1A
	.byte $80, $C0, $0B, $19, $88, $91, $38, $8C, $0A, $1A, $8D, $C0, $1B, $17, $8E, $01
	.byte $37, $9A, $4C, $19, $9A, $92, $19, $9E, $90, $19, $A6, $90, $36, $A7, $26, $3A
	.byte $AC, $A0, $3A, $AA, $90, $1A, $B3, $C0, $06, $38, $B1, $A2, $19, $B8, $90, $39
	.byte $B9, $40, $38, $B9, $40, $37, $B9, $40, $36, $B9, $40, $17, $BE, $01, $1A, $BE
	.byte $C0, $04, $1A, $CC, $C0, $04, $51, $CC, $09, $19, $CF, $90, $0F, $08, $E2, $0E
	.byte $13, $E2, $0F, $1B, $E4, $0E, $24, $E3, $0F, $35, $E2, $0E, $41, $E2, $0F, $49
	.byte $E4, $0E, $53, $E3, $0F, $66, $E2, $0E, $70, $E2, $0F, $79, $E4, $0E, $82, $E3
	.byte $0F, $96, $E2, $0E, $A2, $E2, $10, $A9, $E4, $0E, $B2, $E3, $0F, $C6, $E2, $EA
	.byte $42, $10, $55, $C0, $B0, $00, $55, $BC, $B0, $00, $52, $C3, $B0, $01, $59, $C2
	.byte $B0, $00, $FF