; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.word $0000	; Alternate level layout
	.word $0000	; Alternate object layout
	.byte LEVEL1_SIZE_02 | LEVEL1_YSTART_170
	.byte LEVEL2_BGPAL_04 | LEVEL2_OBJPAL_08 | LEVEL2_XSTART_18
	.byte LEVEL3_TILESET_00 | LEVEL3_VSCROLL_LOCKED
	.byte LEVEL4_BGBANK_INDEX(1) | LEVEL4_INITACT_NOTHING
	.byte LEVEL5_BGM_OVERWORLD | LEVEL5_TIME_300

	.byte $38, $03, $A1, $1A, $00, $C0, $1F, $19, $00, $91, $59, $0B, $B0, $08, $58, $0C
	.byte $B0, $07, $57, $0D, $B0, $06, $56, $0E, $B0, $05, $55, $0F, $B0, $04, $54, $10
	.byte $B0, $03, $53, $11, $B0, $02, $52, $12, $B0, $01, $19, $16, $91, $51, $1C, $09
	.byte $17, $05, $01, $17, $18, $01, $FF