; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.word W501BL	; Alternate level layout
	.word W501BO	; Alternate object layout
	.byte LEVEL1_SIZE_15 | LEVEL1_YSTART_180
	.byte LEVEL2_BGPAL_00 | LEVEL2_OBJPAL_08 | LEVEL2_XSTART_18
	.byte LEVEL3_TILESET_09 | LEVEL3_VSCROLL_LOCKED | LEVEL3_PIPENOTEXIT
	.byte LEVEL4_BGBANK_INDEX(9) | LEVEL4_INITACT_NOTHING
	.byte LEVEL5_BGM_OVERWORLD | LEVEL5_TIME_300

	.byte $16, $2B, $04, $13, $06, $0C, $36, $0C, $23, $16, $14, $04, $0F, $0B, $0A, $10
	.byte $1A, $0A, $0D, $25, $0A, $79, $0E, $23, $19, $17, $0C, $33, $1B, $D4, $7A, $20
	.byte $C4, $33, $29, $D4, $33, $2E, $D1, $33, $32, $D1, $33, $36, $D1, $7A, $2E, $C1
	.byte $7A, $32, $C1, $7A, $36, $C1, $16, $3B, $04, $79, $3E, $23, $18, $46, $0C, $59
	.byte $4A, $30, $57, $4A, $31, $79, $56, $23, $16, $5A, $04, $35, $65, $A4, $36, $57
	.byte $B3, $79, $6E, $23, $38, $73, $A1, $18, $76, $0C, $16, $6B, $04, $79, $7B, $58
	.byte $78, $7C, $57, $77, $7D, $56, $76, $7E, $55, $75, $7F, $54, $74, $80, $53, $73
	.byte $81, $52, $72, $82, $51, $72, $1A, $53, $72, $28, $5F, $7A, $86, $C5, $36, $84
	.byte $0E, $32, $84, $0F, $72, $8C, $52, $73, $8C, $52, $74, $8C, $52, $75, $8C, $52
	.byte $76, $8C, $52, $77, $8C, $52, $78, $8C, $52, $79, $8C, $52, $7A, $8F, $C7, $72
	.byte $97, $53, $73, $97, $53, $74, $97, $53, $75, $97, $53, $76, $97, $53, $77, $97
	.byte $53, $78, $97, $53, $79, $97, $53, $7A, $9B, $C8, $72, $A4, $51, $73, $A4, $51
	.byte $74, $A4, $51, $75, $A4, $51, $76, $A4, $51, $77, $A4, $51, $78, $A4, $51, $79
	.byte $A4, $51, $7A, $AD, $C2, $58, $B5, $31, $79, $B6, $21, $38, $BD, $A1, $33, $BD
	.byte $D2, $72, $BC, $53, $3A, $C5, $A0, $3A, $C9, $A0, $18, $B9, $0C, $18, $CB, $0C
	.byte $79, $CE, $23, $3A, $D3, $A0, $18, $D6, $0C, $79, $E6, $22, $18, $EA, $0C, $36
	.byte $EA, $82, $3A, $ED, $90, $79, $26, $23, $0F, $3B, $0A, $13, $46, $0A, $0E, $57
	.byte $0A, $0F, $62, $0A, $12, $6F, $0A, $0E, $76, $0A, $10, $88, $0A, $0E, $9C, $0A
	.byte $12, $A0, $0A, $0E, $AB, $0A, $12, $B9, $0A, $0C, $BC, $0A, $12, $CE, $0A, $0D
	.byte $DC, $0A, $12, $E7, $0A, $EE, $71, $10, $E5, $02, $10, $FF