; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.word W501CL	; Alternate level layout
	.word W501CO	; Alternate object layout
	.byte LEVEL1_SIZE_09 | LEVEL1_YSTART_170
	.byte LEVEL2_BGPAL_00 | LEVEL2_OBJPAL_08 | LEVEL2_XSTART_18
	.byte LEVEL3_TILESET_09 | LEVEL3_VSCROLL_LOCKED | LEVEL3_PIPENOTEXIT
	.byte LEVEL4_BGBANK_INDEX(9) | LEVEL4_INITACT_NOTHING
	.byte LEVEL5_BGM_OVERWORLD | LEVEL5_TIME_300

	.byte $12, $72, $70, $0F, $54, $77, $E3, $78, $40, $38, $01, $A1, $18, $0F, $0C, $79
	.byte $12, $23, $18, $1A, $0C, $3A, $1D, $A0, $7A, $25, $C4, $7A, $30, $C9, $79, $2A
	.byte $55, $78, $2A, $55, $77, $2A, $55, $76, $2A, $55, $79, $24, $50, $75, $2B, $54
	.byte $74, $2C, $53, $73, $2D, $52, $72, $2E, $51, $36, $3C, $12, $32, $3B, $14, $32
	.byte $3F, $0C, $18, $40, $0C, $79, $43, $22, $18, $4A, $0C, $35, $51, $0E, $32, $52
	.byte $0E, $0F, $56, $84, $12, $54, $84, $15, $54, $84, $18, $54, $77, $15, $72, $60
	.byte $12, $73, $A0, $0F, $55, $A0, $11, $54, $60, $72, $74, $C1, $73, $74, $C1, $16
	.byte $72, $70, $76, $74, $C1, $77, $74, $C1, $16, $73, $A0, $14, $72, $60, $32, $76
	.byte $A7, $7A, $74, $C1, $51, $81, $09, $10, $03, $0A, $14, $10, $0A, $0D, $1F, $0A
	.byte $10, $26, $0A, $13, $08, $0A, $0D, $30, $0A, $0F, $38, $0A, $0C, $43, $0A, $10
	.byte $48, $0A, $0A, $57, $0A, $0D, $61, $0A, $0D, $69, $0A, $0D, $70, $0A, $10, $78
	.byte $0A, $0B, $86, $0A, $12, $8D, $0A, $18, $7E, $0C, $16, $89, $0C, $FF