; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.word W501DL	; Alternate level layout
	.word W501DO	; Alternate object layout
	.byte LEVEL1_SIZE_07 | LEVEL1_YSTART_170
	.byte LEVEL2_BGPAL_00 | LEVEL2_OBJPAL_08 | LEVEL2_XSTART_18
	.byte LEVEL3_TILESET_09 | LEVEL3_VSCROLL_LOCKED | LEVEL3_PIPENOTEXIT
	.byte LEVEL4_BGBANK_INDEX(9) | LEVEL4_INITACT_NOTHING
	.byte LEVEL5_BGM_SPECIAL | LEVEL5_TIME_300

	.byte $7A, $00, $6F, $7A, $10, $6F, $7A, $20, $6F, $7A, $30, $6F, $7A, $40, $6F, $32
	.byte $0E, $8F, $39, $1E, $86, $39, $26, $87, $39, $2F, $8F, $33, $3A, $89, $32, $46
	.byte $87, $30, $53, $88, $7A, $50, $6F, $7A, $60, $9F, $3A, $69, $82, $E6, $48, $20
	.byte $75, $04, $50, $77, $25, $50, $78, $25, $50, $79, $25, $50, $77, $2E, $50, $78
	.byte $2E, $50, $79, $2E, $50, $74, $44, $50, $75, $44, $50, $74, $4E, $50, $75, $4E
	.byte $50, $71, $51, $51, $71, $54, $50, $71, $56, $50, $71, $58, $50, $71, $5A, $50
	.byte $FF