; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.word WZRO2	; Alternate level layout
	.word W6ZROI	; Alternate object layout
	.byte LEVEL1_SIZE_02 | LEVEL1_YSTART_170
	.byte LEVEL2_BGPAL_00 | LEVEL2_OBJPAL_08 | LEVEL2_XSTART_18
	.byte LEVEL3_TILESET_14 | LEVEL3_VSCROLL_LOCKED | LEVEL3_PIPENOTEXIT
	.byte LEVEL4_BGBANK_INDEX(9) | LEVEL4_INITACT_NOTHING
	.byte LEVEL5_BGM_OVERWORLD | LEVEL5_TIME_300

	.byte $38, $02, $A1, $79, $06, $59, $78, $07, $58, $77, $08, $57, $76, $09, $56, $75
	.byte $0A, $55, $74, $0B, $54, $73, $0C, $53, $72, $0D, $52, $71, $0E, $51, $70, $0F
	.byte $5C, $10, $1E, $6D, $11, $1E, $6D, $12, $1E, $6D, $14, $1E, $6D, $13, $1E, $6D
	.byte $15, $1E, $6D, $16, $1E, $6D, $18, $1E, $6D, $19, $1E, $6D, $17, $1E, $6D, $37
	.byte $16, $92, $79, $10, $20, $16, $14, $04, $16, $17, $04, $13, $1B, $0A, $11, $02
	.byte $0A, $0B, $0C, $0A, $12, $12, $0A, $0F, $0A, $0A, $0D, $19, $0A, $E1, $54, $D0
	.byte $0F, $1E, $6D, $FF