; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.word $0000	; Alternate level layout
	.word $0000	; Alternate object layout
	.byte LEVEL1_SIZE_02 | LEVEL1_YSTART_0F0
	.byte LEVEL2_BGPAL_03 | LEVEL2_OBJPAL_09 | LEVEL2_XSTART_D8
	.byte LEVEL3_TILESET_01 | LEVEL3_VSCROLL_LOCKED
	.byte LEVEL4_BGBANK_INDEX(20) | LEVEL4_INITACT_PIPE_B
	.byte LEVEL5_BGM_BOSS | LEVEL5_TIME_UNLIMITED

	.byte $0F, $04, $B7, $16, $0D, $B2, $16, $0C, $C3, $77, $0D, $62, $78, $0D, $62, $79
	.byte $0D, $62, $7A, $0D, $62, $10, $0B, $B2, $10, $02, $B2, $11, $0D, $B1, $12, $0E
	.byte $B1, $13, $0F, $A2, $17, $0D, $A2, $11, $01, $B1, $12, $00, $B1, $12, $00, $A3
	.byte $16, $00, $B2, $17, $02, $A2, $12, $0D, $C0, $11, $0C, $C0, $13, $0E, $C2, $1A
	.byte $02, $BB, $6F, $00, $63, $6F, $0C, $63, $70, $0E, $61, $71, $0F, $60, $70, $00
	.byte $61, $71, $00, $60, $77, $00, $73, $77, $01, $73, $16, $0A, $0A, $15, $03, $CB
	.byte $12, $08, $09, $4C, $08, $70, $00, $FF