; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.byte $00	; Unknown purpose

	.byte OBJ_PARATROOPAGREENHOP, $10, $15
	.byte OBJ_REDTROOPA, $14, $15
	.byte OBJ_GREENPIRANHA, $20, $1A
	.byte OBJ_GREENPIRANHA, $27, $16
	.byte OBJ_GREENPIRANHA, $2D, $1A
	.byte OBJ_GOOMBA, $2E, $19
	.byte OBJ_GOOMBA, $2F, $19
	.byte OBJ_GREENTROOPA, $41, $19
	.byte OBJ_PARATROOPAGREENHOP, $47, $15
	.byte OBJ_GREENTROOPA, $55, $19
	.byte OBJ_GREENTROOPA, $55, $15
	.byte OBJ_GREENTROOPA, $56, $19
	.byte OBJ_GREENTROOPA, $56, $15
	.byte OBJ_REDTROOPA, $58, $11
	.byte OBJ_CHECKPOINT_FORCE, $63, $19
	.byte OBJ_GOOMBA, $66, $19
	.byte OBJ_GOOMBA, $67, $19
	.byte OBJ_GREENTROOPA, $73, $19
	.byte OBJ_GREENTROOPA, $74, $19
	.byte OBJ_GREENTROOPA, $75, $19
	.byte OBJ_PARATROOPAGREENHOP, $7B, $15
	.byte OBJ_GREENPIRANHA, $7B, $16
	.byte OBJ_GREENPIRANHA, $80, $16
	.byte OBJ_GREENPIRANHA, $90, $16
	.byte OBJ_GREENTROOPA, $91, $15
	.byte OBJ_GREENPIRANHA, $95, $13
	.byte OBJ_REDTROOPA, $98, $19
	.byte OBJ_REDTROOPA, $A2, $19
	.byte OBJ_GREENPIRANHA, $A4, $18
	.byte OBJ_GOOMBA, $AB, $19
	.byte OBJ_ENDLEVELCARD, $BD, $11
	.byte OBJ_ENDLEVELCARD, $C8, $15
	.byte $FF
