; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.byte $00	; Unknown purpose

	.byte OBJ_PARATROOPAGREENHOP, $0F, $18
	.byte OBJ_GREENPIRANHA, $23, $16
	.byte OBJ_GOOMBA, $2A, $19
	.byte OBJ_GOOMBA, $2B, $19
	.byte OBJ_GREENPIRANHA, $30, $16
	.byte OBJ_ALTLEVELMOD, $34, $02
	.byte OBJ_BUZZYBEATLE, $34, $19
	.byte OBJ_TOUCHWARP, $34, $00
	.byte OBJ_WOODENPLATUNSTABLE, $41, $17
	.byte OBJ_WOODENPLATUNSTABLE, $49, $16
	.byte OBJ_WOODENPLATUNSTABLE, $51, $15
	.byte OBJ_WOODENPLATUNSTABLE, $59, $14
	.byte OBJ_CHECKPOINT_FORCE, $62, $19
	.byte OBJ_GREENPIRANHA, $65, $16
	.byte OBJ_GREENPIRANHA, $6B, $13
	.byte OBJ_GREENPIRANHA, $6F, $17
	.byte OBJ_GREENPIRANHA, $73, $18
	.byte OBJ_GREENPIRANHA, $77, $15
	.byte OBJ_GREENPIRANHA, $81, $18
	.byte OBJ_GREENTROOPA, $8A, $19
	.byte OBJ_GREENTROOPA, $8B, $19
	.byte OBJ_GREENTROOPA, $8C, $19
	.byte OBJ_WOODENPLATUNSTABLE, $95, $15
	.byte OBJ_OSCILLATING_V, $9B, $17
	.byte OBJ_ALTLEVELMOD, $A8, $01
	.byte OBJ_GREENPIRANHA, $BF, $18
	.byte OBJ_GREENPIRANHA, $C4, $17
	.byte $FF
