; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.byte $00	; Unknown purpose

	.byte OBJ_WOODENPLATUNSTABLE, $10, $16
	.byte OBJ_GREENPIRANHA, $14, $16
	.byte OBJ_GREENPIRANHA, $1A, $16
	.byte OBJ_WOODENPLATUNSTABLE, $21, $16
	.byte OBJ_GREENPIRANHA, $28, $17
	.byte OBJ_GREENPIRANHA, $34, $18
	.byte OBJ_REDTROOPA, $38, $19
	.byte $FF
