; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.byte $00	; Unknown purpose

	.byte OBJ_TOUCHWARP, $00, $03
	.byte OBJ_TOUCHWARP, $0C, $03
	.byte OBJ_TOUCHWARP, $19, $03
	.byte OBJ_TOUCHWARP, $26, $03
	.byte $FF
