; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.byte $00	; Unknown purpose

	.byte OBJ_WOODENPLATUNSTABLE, $19, $12
	.byte OBJ_WOODENPLATUNSTABLE, $1F, $14
	.byte OBJ_REDTROOPA, $2D, $11
	.byte OBJ_REDTROOPA, $33, $18
	.byte OBJ_REDTROOPA, $35, $18
	.byte OBJ_BLOOPER, $39, $13
	.byte OBJ_FLYINGREDPARATROOPA, $3F, $12
	.byte OBJ_OSCILLATING_HS, $46, $16
	.byte OBJ_BLOOPER, $53, $11
	.byte OBJ_WOODENPLATUNSTABLE, $58, $12
	.byte OBJ_WOODENPLATUNSTABLE, $5C, $15
	.byte OBJ_REDTROOPA, $65, $19
	.byte OBJ_CHECKPOINT_FORCE, $74, $15
	.byte OBJ_REDTROOPA, $77, $15
	.byte OBJ_REDTROOPA, $82, $15
	.byte OBJ_OSCILLATING_HS, $86, $13
	.byte OBJ_WOODENPLATUNSTABLE, $8A, $11
	.byte OBJ_WOODENPLATUNSTABLE, $91, $16
	.byte OBJ_ENDLEVELCARD, $AA, $11
	.byte $FF
