; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.byte $00	; Unknown purpose

	.byte OBJ_THWOMP, $13, $12
	.byte OBJ_PIPERAISE1, $1E, $07
	.byte OBJ_ACTIONSWITCH, $1F, $03
	.byte OBJ_THWOMP, $25, $12
	.byte OBJ_THWOMP, $2B, $01
	.byte OBJ_THWOMP, $2D, $10
	.byte OBJ_THWOMP, $33, $10
	.byte OBJ_THWOMP, $44, $11
	.byte OBJ_THWOMP, $4D, $11
	.byte OBJ_GREENTROOPA, $54, $14
	.byte OBJ_THWOMP, $56, $11
	.byte OBJ_THWOMP, $5E, $11
	.byte OBJ_BOSSATTACK, $78, $15
	.byte OBJ_BOSSATTACK, $7D, $13
	.byte OBJ_BOSSATTACK, $80, $14
	.byte OBJ_BOSS_BOWSER, $8B, $14
	.byte OBJ_ACTIONSWITCH, $8D, $01
	.byte OBJ_TOAD, $99, $18
	.byte $FF
