; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.byte $00	; Unknown purpose

	.byte OBJ_PARATROOPAGREENHOP, $12, $13
	.byte OBJ_GREENPIRANHA, $14, $17
	.byte OBJ_GOOMBA, $1A, $19
	.byte OBJ_GREENPIRANHA, $1B, $1A
	.byte OBJ_GOOMBA, $1C, $19
	.byte OBJ_GOOMBA, $1D, $19
	.byte OBJ_GREENPIRANHA, $21, $1A
	.byte OBJ_GREENTROOPA, $26, $19
	.byte OBJ_GREENTROOPA, $27, $19
	.byte OBJ_GREENTROOPA, $29, $19
	.byte OBJ_GREENPIRANHA, $38, $17
	.byte OBJ_GREENTROOPA, $40, $19
	.byte OBJ_GREENTROOPA, $42, $19
	.byte OBJ_PARATROOPAGREENHOP, $4B, $19
	.byte OBJ_PARATROOPAGREENHOP, $4F, $19
	.byte OBJ_GREENPIRANHA, $61, $19
	.byte OBJ_GOOMBA, $6D, $19
	.byte OBJ_GOOMBA, $6F, $19
	.byte OBJ_PARATROOPAGREENHOP, $75, $19
	.byte OBJ_GREENTROOPA, $87, $19
	.byte OBJ_GREENTROOPA, $89, $19
	.byte OBJ_GREENTROOPA, $8A, $19
	.byte OBJ_GREENTROOPA, $8C, $19
	.byte OBJ_GREENTROOPA, $92, $19
	.byte OBJ_GREENTROOPA, $93, $19
	.byte OBJ_CHECKPOINT_FORCE, $99, $19
	.byte OBJ_GREENTROOPA, $9F, $19
	.byte OBJ_GREENTROOPA, $A2, $19
	.byte OBJ_GREENPIRANHA, $AA, $17
	.byte OBJ_GREENTROOPA, $AD, $19
	.byte OBJ_GREENPIRANHA, $B4, $18
	.byte OBJ_REDTROOPA, $BB, $19
	.byte OBJ_GREENPIRANHA, $BF, $10
	.byte OBJ_GREENTROOPA, $CC, $19
	.byte OBJ_GREENTROOPA, $CE, $19
	.byte OBJ_GREENPIRANHA, $DA, $18
	.byte OBJ_ALTLEVELMOD, $DA, $06
	.byte $FF
