; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.byte $00	; Unknown purpose

	.byte OBJ_ACTIONSWITCH, $00, $03
	.byte OBJ_GREENPIRANHA, $01, $18
	.byte OBJ_REDTROOPA, $09, $19
	.byte OBJ_GOOMBA, $0D, $19
	.byte OBJ_GOOMBA, $0F, $19
	.byte OBJ_PARATROOPAGREENHOP, $14, $13
	.byte OBJ_GOOMBA, $21, $11
	.byte OBJ_GOOMBA, $22, $11
	.byte OBJ_GOOMBA, $23, $11
	.byte OBJ_ENDLEVELCARD, $2D, $11
	.byte OBJ_PARABEETLESBEGIN, $36, $03
	.byte OBJ_CANCELEVENT, $41, $03
	.byte OBJ_GREENPIRANHA_FIRE, $50, $06
	.byte OBJ_PARATROOPAGREENHOP, $56, $17
	.byte OBJ_PARATROOPAGREENHOP, $59, $16
	.byte OBJ_PARATROOPAGREENHOP, $5C, $17
	.byte OBJ_SHYGUY_RED, $6A, $05
	.byte OBJ_SHYGUY_RED, $6C, $05
	.byte OBJ_CHECKPOINT, $76, $12
	.byte OBJ_GREENPIRANHA_FIRE_X, $7D, $04
	.byte OBJ_GREENPIRANHA_FIRE, $7F, $0B
	.byte OBJ_ENDLEVELCARD, $98, $10
	.byte $FF
