; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.byte $00	; Unknown purpose

	.byte OBJ_CHEEPCHEEPBEGIN, $15, $16
	.byte OBJ_GREENTROOPA, $19, $15
	.byte OBJ_GREENTROOPA, $1A, $15
	.byte OBJ_GREENTROOPA, $1C, $15
	.byte OBJ_PARATROOPAGREENHOP, $31, $16
	.byte OBJ_FLYINGREDPARATROOPA, $3D, $13
	.byte OBJ_REDTROOPA, $56, $18
	.byte OBJ_BLOOPER, $5B, $16
	.byte OBJ_CHECKPOINT_FORCE, $5F, $19
	.byte OBJ_CHEEPCHEEPBEGIN, $5F, $18
	.byte OBJ_FLYINGGREENPARATROOPA, $75, $14
	.byte OBJ_PARATROOPAGREENHOP, $90, $16
	.byte OBJ_REDTROOPA, $97, $18
	.byte OBJ_CANCELEVENT, $9A, $18
	.byte OBJ_ENDLEVELCARD, $AD, $11
	.byte $FF
