; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.byte $00	; Unknown purpose

	.byte OBJ_GREENTROOPA, $14, $12
	.byte OBJ_GOOMBA, $19, $19
	.byte OBJ_GOOMBA, $1A, $19
	.byte OBJ_GOOMBA, $1C, $19
	.byte OBJ_GREENTROOPA, $24, $19
	.byte OBJ_GREENTROOPA, $26, $19
	.byte OBJ_GREENTROOPA, $2E, $19
	.byte OBJ_GREENTROOPA, $2F, $19
	.byte OBJ_GREENTROOPA, $31, $19
	.byte OBJ_THWOMP, $33, $12
	.byte OBJ_THWOMP, $49, $11
	.byte OBJ_THWOMP, $4D, $11
	.byte OBJ_PODOBOO, $4E, $13
	.byte OBJ_THWOMP, $52, $11
	.byte OBJ_THWOMP, $58, $11
	.byte OBJ_PODOBOO, $5E, $12
	.byte OBJ_THWOMP, $63, $10
	.byte OBJ_THWOMP, $6A, $13
	.byte OBJ_PODOBOO, $72, $13
	.byte OBJ_BOSS_BOWSER, $8B, $14
	.byte OBJ_ACTIONSWITCH, $8D, $01
	.byte OBJ_TOAD, $99, $18
	.byte $FF
