; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.byte $00	; Unknown purpose

	.byte OBJ_WOODENPLAT_RIDER, $10, $17
	.byte OBJ_TOUCHWARP, $55, $03
	.byte OBJ_TOUCHWARP, $6A, $03
	.byte OBJ_TOUCHWARP, $7F, $03
	.byte $FF
