; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.byte $00	; Unknown purpose

	.byte OBJ_BLOOPER, $12, $18
	.byte OBJ_GREENCHEEP, $19, $15
	.byte OBJ_BLOOPER, $1E, $17
	.byte OBJ_GREENCHEEP, $29, $16
	.byte OBJ_GREENCHEEP, $2E, $14
	.byte OBJ_GREENCHEEP, $3A, $15
	.byte OBJ_BLOOPER, $3F, $17
	.byte OBJ_GREENCHEEP, $46, $12
	.byte OBJ_CHECKPOINT_FORCE, $47, $16
	.byte OBJ_GREENTROOPA, $4B, $16
	.byte OBJ_BLOOPER, $52, $15
	.byte OBJ_GREENCHEEP, $5B, $11
	.byte OBJ_BLOOPER, $63, $18
	.byte OBJ_GREENCHEEP, $65, $14
	.byte OBJ_FLYINGREDPARATROOPA, $69, $11
	.byte OBJ_GREENCHEEP, $74, $18
	.byte OBJ_BLOOPER, $76, $12
	.byte OBJ_GREENCHEEP, $80, $12
	.byte OBJ_REDTROOPA, $82, $15
	.byte OBJ_BLOOPER, $88, $15
	.byte OBJ_GREENCHEEP, $8E, $12
	.byte OBJ_GREENCHEEP, $98, $16
	.byte OBJ_GREENCHEEP, $9B, $10
	.byte OBJ_GREENCHEEP, $A4, $18
	.byte OBJ_BLOOPER, $A6, $10
	.byte OBJ_GREENCHEEP, $A8, $14
	.byte OBJ_BLOOPER, $AE, $14
	.byte OBJ_REDTROOPA, $B3, $19
	.byte OBJ_GREENCHEEP, $B7, $14
	.byte $FF
