; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.byte $00	; Unknown purpose

	.byte OBJ_GREENPIRANHA, $27, $17
	.byte OBJ_GREENPIRANHA, $55, $16
	.byte OBJ_GREENPIRANHA, $59, $16
	.byte OBJ_PIPERAISE1, $7B, $0A
	.byte OBJ_THWOMPUPDOWN, $7B, $16
	.byte OBJ_ACTIONSWITCH, $7C, $03
	.byte OBJ_THWOMPUPDOWN, $87, $16
	.byte OBJ_BOSS_BOWSER, $AA, $14
	.byte OBJ_ACTIONSWITCH, $AC, $01
	.byte OBJ_TOAD, $B9, $18
	.byte OBJ_TOAD, $B9, $18
	.byte OBJ_TOAD, $B9, $18
	.byte OBJ_TOAD, $B9, $18
	.byte $FF
