; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.byte $00	; Unknown purpose

	.byte OBJ_GREENPIRANHA, $19, $18
	.byte OBJ_LAKITU, $1D, $10
	.byte OBJ_GREENPIRANHA, $1E, $1A
	.byte OBJ_GREENPIRANHA, $34, $16
	.byte OBJ_LAKITUFLEE, $4A, $12
	.byte OBJ_LAKITU, $68, $10
	.byte OBJ_CHECKPOINT_FORCE, $70, $19
	.byte OBJ_GREENPIRANHA, $7C, $15
	.byte OBJ_GREENPIRANHA, $95, $13
	.byte OBJ_GREENPIRANHA, $97, $13
	.byte OBJ_GREENPIRANHA, $99, $13
	.byte OBJ_GREENPIRANHA, $A0, $18
	.byte OBJ_ALTLEVELMOD, $A7, $03
	.byte OBJ_TOUCHWARP, $A7, $00
	.byte OBJ_GREENPIRANHA, $A8, $17
	.byte OBJ_GREENPIRANHA, $AD, $16
	.byte OBJ_GOOMBA, $BA, $11
	.byte OBJ_LAKITUFLEE, $C2, $11
	.byte OBJ_ENDLEVELCARD, $C4, $11
	.byte $FF
