; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.byte $00	; Unknown purpose

	.byte OBJ_GREENTROOPA, $25, $19
	.byte OBJ_BLOOPER, $27, $12
	.byte OBJ_BLOOPER, $2D, $16
	.byte OBJ_GREENTROOPA, $2E, $16
	.byte OBJ_BLOOPER, $42, $14
	.byte $FF
