; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.byte $00	; Unknown purpose

	.byte OBJ_WOODENPLAT_RIDER, $10, $17
	.byte OBJ_TOUCHWARP, $56, $03
	.byte OBJ_TOUCHWARP, $6C, $03
	.byte OBJ_TOUCHWARP, $7E, $03
	.byte $FF
