; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.byte $00	; Unknown purpose

	.byte OBJ_CFIRE_BULLETBILL, $11, $18
	.byte OBJ_CFIRE_BULLETBILL, $11, $16
	.byte OBJ_CFIRE_BULLETBILL, $16, $17
	.byte OBJ_CFIRE_BULLETBILL, $16, $19
	.byte OBJ_CFIRE_BULLETBILL, $19, $15
	.byte OBJ_BUZZYBEATLE, $28, $19
	.byte OBJ_BUZZYBEATLE, $29, $19
	.byte OBJ_REDTROOPA, $3F, $11
	.byte OBJ_LAKITUFLEE, $46, $11
	.byte OBJ_LAKITU, $47, $10
	.byte OBJ_CHECKPOINT_FORCE, $4D, $19
	.byte OBJ_GOOMBA, $51, $19
	.byte OBJ_GOOMBA, $53, $19
	.byte OBJ_GREENTROOPA, $5B, $19
	.byte OBJ_GREENTROOPA, $5C, $19
	.byte OBJ_GREENTROOPA, $5E, $19
	.byte OBJ_GREENTROOPA, $6B, $19
	.byte OBJ_GREENTROOPA, $6D, $19
	.byte OBJ_GREENPIRANHA, $73, $15
	.byte OBJ_CFIRE_BULLETBILL, $79, $18
	.byte OBJ_REDTROOPA, $7E, $19
	.byte OBJ_CFIRE_BULLETBILL, $81, $19
	.byte OBJ_LAKITU, $85, $10
	.byte OBJ_LAKITUFLEE, $86, $11
	.byte OBJ_REDTROOPA, $8A, $19
	.byte OBJ_HAMMERBRO, $94, $18
	.byte OBJ_GREENPIRANHA, $AA, $1A
	.byte OBJ_HAMMERBRO, $AB, $13
	.byte OBJ_GREENPIRANHA, $AC, $1A
	.byte OBJ_GREENPIRANHA, $B1, $18
	.byte OBJ_FLYINGGREENPARATROOPA, $C4, $10
	.byte OBJ_ENDLEVELCARD, $CC, $11
	.byte $FF
