; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.byte $00	; Unknown purpose

	.byte OBJ_THWOMP, $12, $10
	.byte OBJ_REDTROOPA, $15, $15
	.byte OBJ_THWOMP, $26, $11
	.byte OBJ_GOOMBA, $26, $15
	.byte OBJ_GOOMBA, $28, $15
	.byte OBJ_THWOMP, $34, $0E
	.byte OBJ_THWOMP, $3A, $10
	.byte OBJ_THWOMP, $52, $0E
	.byte OBJ_GREENTROOPA, $58, $12
	.byte OBJ_GREENTROOPA, $59, $12
	.byte OBJ_GREENTROOPA, $5B, $12
	.byte OBJ_WOODENPLATUNSTABLE, $5D, $13
	.byte OBJ_THWOMP, $65, $10
	.byte OBJ_HAMMERBRO, $6E, $18
	.byte OBJ_GREENPIRANHA, $7E, $13
	.byte OBJ_THWOMP, $82, $0E
	.byte OBJ_GREENTROOPA, $9B, $19
	.byte OBJ_GREENTROOPA, $9C, $19
	.byte OBJ_GREENTROOPA, $9E, $19
	.byte OBJ_GREENPIRANHA, $A6, $19
	.byte OBJ_OSCILLATING_HS, $AE, $19
	.byte OBJ_BOSS_BOWSER, $CB, $14
	.byte OBJ_ACTIONSWITCH, $CD, $01
	.byte OBJ_TOAD, $D9, $18
	.byte $FF
