; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.byte $00	; Unknown purpose

	.byte OBJ_GREENPIRANHA, $01, $18
	.byte OBJ_GREENTROOPA, $09, $19
	.byte OBJ_GREENTROOPA, $0A, $19
	.byte OBJ_GREENTROOPA, $0C, $19
	.byte OBJ_GREENTROOPA, $1D, $19
	.byte OBJ_GREENPIRANHA, $1D, $1A
	.byte OBJ_GREENTROOPA, $1E, $19
	.byte OBJ_GREENTROOPA, $20, $19
	.byte OBJ_FLYINGREDPARATROOPA, $36, $12
	.byte OBJ_FLYINGREDPARATROOPA, $39, $12
	.byte OBJ_TOUCHWARP, $3F, $00
	.byte OBJ_FLYINGREDPARATROOPA, $41, $11
	.byte OBJ_PARATROOPAGREENHOP, $50, $19
	.byte OBJ_PARATROOPAGREENHOP, $53, $17
	.byte OBJ_GREENPIRANHA, $76, $12
	.byte OBJ_ENDLEVELCARD, $81, $11
	.byte $FF
