; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.byte $00	; Unknown purpose

	.byte OBJ_GROWINGVINE, $04, $1A
	.byte OBJ_WOODENPLAT_RIDER, $0E, $17
	.byte OBJ_TOUCHWARP, $63, $03
	.byte OBJ_TOUCHWARP, $6E, $03
	.byte $FF
