; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.byte $00	; Unknown purpose

	.byte OBJ_GREENPIRANHA, $03, $18
	.byte OBJ_ENDLEVELCARD, $1C, $11
	.byte $FF
