; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.byte $00	; Unknown purpose

	.byte OBJ_DRYBONES, $06, $17
	.byte OBJ_DRYBONES, $06, $16
	.byte OBJ_DRYBONES, $07, $15
	.byte OBJ_DRYBONES, $07, $16
	.byte OBJ_DRYBONES, $07, $17
	.byte OBJ_DRYBONES, $08, $16
	.byte OBJ_DRYBONES, $08, $17
	.byte OBJ_DRYBONES, $09, $17
	.byte OBJ_DRYBONES, $0A, $15
	.byte OBJ_DRYBONES, $0A, $17
	.byte OBJ_DRYBONES, $0A, $16
	.byte OBJ_DRYBONES, $0C, $16
	.byte OBJ_DRYBONES, $0C, $15
	.byte $FF
