; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.word W102BL	; Alternate level layout
	.word W102BO	; Alternate object layout
	.byte LEVEL1_SIZE_04 | LEVEL1_YSTART_170
	.byte LEVEL2_BGPAL_00 | LEVEL2_OBJPAL_08 | LEVEL2_XSTART_18
	.byte LEVEL3_TILESET_01 | LEVEL3_VSCROLL_LOCKED | LEVEL3_PIPENOTEXIT
	.byte LEVEL4_BGBANK_INDEX(4) | LEVEL4_INITACT_NOTHING
	.byte LEVEL5_BGM_SPECIAL | LEVEL5_TIME_300

	.byte $7A, $00, $93, $16, $0D, $10, $02, $1A, $11, $10, $04, $39, $12, $82, $39, $06
	.byte $82, $35, $0D, $82, $12, $15, $10, $03, $31, $16, $81, $13, $16, $04, $13, $17
	.byte $04, $16, $19, $10, $07, $35, $1A, $85, $17, $1A, $04, $17, $1C, $04, $17, $1E
	.byte $04, $17, $1F, $04, $17, $1D, $04, $17, $1B, $04, $35, $04, $40, $39, $28, $48
	.byte $38, $29, $47, $37, $2A, $46, $36, $2B, $45, $35, $2C, $44, $34, $2D, $43, $33
	.byte $2E, $42, $32, $2F, $41, $31, $30, $4B, $37, $36, $92, $17, $0E, $04, $1A, $27
	.byte $10, $18, $4F, $3E, $BA, $01, $36, $31, $0B, $E3, $42, $06, $16, $04, $08, $7A
	.byte $05, $94, $E0, $4F, $30, $E1, $4F, $30, $E2, $4F, $30, $FF