; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.word W201AL	; Alternate level layout
	.word W201AO	; Alternate object layout
	.byte LEVEL1_SIZE_01 | LEVEL1_YSTART_170
	.byte LEVEL2_BGPAL_04 | LEVEL2_OBJPAL_09 | LEVEL2_XSTART_18
	.byte LEVEL3_TILESET_04 | LEVEL3_VSCROLL_LOCKED | LEVEL3_PIPENOTEXIT
	.byte LEVEL4_BGBANK_INDEX(23) | LEVEL4_INITACT_NOTHING
	.byte LEVEL5_BGM_UNDERGROUND | LEVEL5_TIME_300

	.byte $2F, $0F, $DB, $E4, $4F, $B8, $E3, $6F, $F7, $5A, $00, $D1, $0F, $7A, $03, $E0
	.byte $00, $39, $00, $10, $38, $00, $10, $37, $00, $10, $36, $00, $10, $35, $00, $10
	.byte $34, $00, $10, $33, $00, $10, $32, $00, $10, $31, $00, $10, $30, $00, $10, $2F
	.byte $00, $10, $2F, $04, $1A, $30, $04, $10, $31, $04, $10, $32, $04, $10, $33, $04
	.byte $10, $34, $04, $10, $36, $04, $16, $35, $04, $10, $37, $0B, $10, $38, $0B, $10
	.byte $37, $06, $10, $38, $06, $10, $36, $0B, $0A, $35, $05, $85, $39, $07, $83, $38
	.byte $0D, $E1, $2F, $01, $D1, $E0, $71, $45, $FF