; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.word W201AL	; Alternate level layout
	.word W201AO	; Alternate object layout
	.byte LEVEL1_SIZE_08 | LEVEL1_YSTART_000
	.byte LEVEL2_BGPAL_06 | LEVEL2_OBJPAL_08 | LEVEL2_XSTART_18
	.byte LEVEL3_TILESET_04 | LEVEL3_VSCROLL_LOCKED | LEVEL3_PIPENOTEXIT
	.byte LEVEL4_BGBANK_INDEX(23) | LEVEL4_INITACT_NOTHING
	.byte LEVEL5_BGM_SPECIAL | LEVEL5_TIME_300

	.byte $E3, $08, $1A, $E0, $78, $80, $65, $3B, $D5, $6E, $27, $D2, $7A, $00, $94, $7A
	.byte $05, $9F, $7A, $15, $9F, $7A, $25, $9F, $16, $04, $08, $16, $04, $40, $32, $10
	.byte $8F, $32, $20, $10, $31, $20, $10, $30, $20, $10, $33, $20, $10, $34, $20, $10
	.byte $35, $20, $10, $2F, $20, $10, $32, $22, $8D, $76, $30, $9F, $39, $31, $8D, $7A
	.byte $35, $9F, $32, $40, $8F, $7A, $45, $9E, $32, $5F, $8B, $3A, $6C, $82, $E5, $4F
	.byte $6C, $E6, $4F, $6C, $E7, $4F, $6C, $FF