; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.word W202CL	; Alternate level layout
	.word W202CO	; Alternate object layout
	.byte LEVEL1_SIZE_14 | LEVEL1_YSTART_180
	.byte LEVEL2_BGPAL_04 | LEVEL2_OBJPAL_08 | LEVEL2_XSTART_18
	.byte LEVEL3_TILESET_04 | LEVEL3_VSCROLL_LOCKED | LEVEL3_PIPENOTEXIT
	.byte LEVEL4_BGBANK_INDEX(23) | LEVEL4_INITACT_NOTHING
	.byte LEVEL5_BGM_MARIOLAND | LEVEL5_TIME_300

	.byte $6E, $50, $D9, $E0, $13, $40, $7A, $00, $B0, $F0, $37, $14, $A2, $3A, $1B, $A0
	.byte $3A, $21, $A0, $18, $1E, $00, $10, $14, $01, $15, $08, $00, $11, $02, $01, $14
	.byte $25, $00, $13, $28, $00, $7A, $2E, $E0, $04, $7A, $36, $E0, $01, $18, $30, $00
	.byte $38, $33, $40, $39, $33, $41, $35, $2A, $82, $37, $38, $A3, $14, $3B, $00, $10
	.byte $36, $01, $35, $41, $83, $39, $52, $40, $7A, $53, $E0, $03, $18, $4E, $00, $0F
	.byte $44, $01, $39, $57, $44, $38, $57, $43, $37, $57, $42, $36, $57, $41, $7A, $5D
	.byte $E0, $0B, $14, $55, $00, $13, $58, $00, $39, $61, $A1, $18, $60, $00, $34, $62
	.byte $85, $10, $65, $01, $39, $68, $41, $14, $6B, $00, $39, $7A, $40, $7A, $7B, $E0
	.byte $02, $7A, $7F, $E0, $01, $39, $7E, $40, $38, $7E, $40, $0F, $75, $01, $33, $7E
	.byte $08, $37, $AA, $92, $39, $AF, $40, $38, $AF, $40, $36, $AE, $0A, $32, $AE, $06
	.byte $7A, $B0, $E0, $03, $38, $B4, $A1, $14, $85, $00, $13, $88, $00, $35, $8E, $82
	.byte $18, $90, $00, $33, $99, $83, $14, $9B, $00, $10, $95, $01, $18, $AE, $00, $14
	.byte $B5, $00, $13, $B8, $00, $7A, $BD, $E0, $09, $18, $C0, $00, $39, $C7, $40, $38
	.byte $C7, $40, $35, $BB, $0E, $32, $BA, $0E, $30, $BF, $A1, $32, $BF, $41, $10, $C5
	.byte $01, $14, $CB, $00, $38, $D3, $40, $39, $D3, $40, $37, $D3, $40, $35, $CF, $81
	.byte $7A, $DC, $E0, $01, $0F, $D4, $01, $18, $DE, $00, $38, $DA, $91, $EA, $42, $10
	.byte $ED, $71, $10, $FF