; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.word W202BL	; Alternate level layout
	.word W202BO	; Alternate object layout
	.byte LEVEL1_SIZE_03 | LEVEL1_YSTART_170
	.byte LEVEL2_BGPAL_04 | LEVEL2_OBJPAL_08 | LEVEL2_XSTART_18
	.byte LEVEL3_TILESET_04 | LEVEL3_VSCROLL_LOCKED | LEVEL3_PIPENOTEXIT
	.byte LEVEL4_BGBANK_INDEX(23) | LEVEL4_INITACT_NOTHING
	.byte LEVEL5_BGM_MARIOLAND | LEVEL5_TIME_300

	.byte $38, $01, $A1, $7A, $00, $B0, $30, $7A, $03, $E0, $01, $18, $05, $00, $7A, $13
	.byte $E0, $07, $35, $14, $42, $51, $2D, $09, $18, $16, $00, $14, $0E, $00, $15, $0B
	.byte $00, $10, $1B, $01, $35, $1D, $40, $10, $2B, $01, $52, $23, $B7, $01, $59, $1C
	.byte $B0, $06, $58, $1D, $B0, $06, $57, $1E, $B0, $06, $56, $1F, $B0, $05, $55, $20
	.byte $B0, $04, $54, $21, $B0, $03, $53, $22, $B0, $02, $FF