; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.word W202AL	; Alternate level layout
	.word W202AO	; Alternate object layout
	.byte LEVEL1_SIZE_01 | LEVEL1_YSTART_170
	.byte LEVEL2_BGPAL_04 | LEVEL2_OBJPAL_09 | LEVEL2_XSTART_18
	.byte LEVEL3_TILESET_04 | LEVEL3_VSCROLL_LOCKED | LEVEL3_PIPENOTEXIT
	.byte LEVEL4_BGBANK_INDEX(23) | LEVEL4_INITACT_NOTHING
	.byte LEVEL5_BGM_UNDERGROUND | LEVEL5_TIME_300

	.byte $2F, $0F, $DB, $39, $00, $10, $38, $00, $10, $37, $00, $10, $36, $00, $10, $35
	.byte $00, $10, $34, $00, $10, $33, $00, $10, $32, $00, $10, $31, $00, $10, $30, $00
	.byte $10, $2F, $00, $10, $5A, $00, $D1, $0F, $37, $05, $87, $39, $03, $89, $38, $0D
	.byte $E1, $2F, $03, $1B, $2F, $03, $06, $36, $03, $0E, $33, $04, $0E, $36, $01, $0E
	.byte $6D, $01, $E3, $01, $E0, $71, $4B, $FF