; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.word $0000	; Alternate level layout
	.word $0000	; Alternate object layout
	.byte LEVEL1_SIZE_12 | LEVEL1_YSTART_180
	.byte LEVEL2_BGPAL_00 | LEVEL2_OBJPAL_08 | LEVEL2_XSTART_18
	.byte LEVEL3_TILESET_00 | LEVEL3_VSCROLL_LOCKED
	.byte LEVEL4_BGBANK_INDEX(4) | LEVEL4_INITACT_NOTHING
	.byte LEVEL5_BGM_ATHLETIC | LEVEL5_TIME_300

	.byte $1A, $00, $10, $0F, $1A, $18, $10, $03, $33, $21, $81, $03, $06, $C2, $18, $1D
	.byte $00, $14, $0A, $00, $10, $04, $01, $0F, $13, $01, $14, $24, $00, $13, $27, $00
	.byte $18, $30, $00, $11, $35, $01, $16, $3D, $10, $04, $17, $3E, $04, $17, $3F, $04
	.byte $17, $40, $04, $15, $3C, $00, $16, $4E, $10, $06, $17, $4F, $04, $17, $50, $04
	.byte $17, $51, $04, $17, $52, $04, $17, $53, $04, $10, $45, $01, $35, $4F, $84, $1A
	.byte $54, $10, $02, $14, $56, $00, $13, $59, $00, $31, $59, $81, $36, $5C, $00, $18
	.byte $61, $00, $1A, $63, $10, $05, $16, $6B, $10, $03, $17, $6C, $04, $17, $6D, $04
	.byte $14, $6D, $00, $10, $66, $01, $30, $7D, $80, $30, $7F, $80, $0F, $76, $01, $18
	.byte $80, $00, $1A, $83, $10, $0F, $12, $8D, $04, $12, $8B, $04, $12, $8C, $04, $12
	.byte $8A, $04, $12, $89, $04, $11, $88, $10, $06, $13, $87, $00, $18, $92, $00, $30
	.byte $89, $84, $1A, $9C, $10, $0C, $30, $9A, $82, $13, $9D, $00, $0F, $97, $01, $0E
	.byte $A5, $01, $18, $AF, $00, $14, $B6, $00, $13, $B9, $00, $51, $BB, $09, $1A, $BB
	.byte $10, $0C, $56, $AD, $B0, $00, $52, $B2, $B0, $00, $FF