; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
W2_InitIndex:	.byte $00, (W2_ByRowType_S2 - W2_ByRowType), (W2_ByRowType_S3 - W2_ByRowType), (W2_ByRowType_S4 - W2_ByRowType)
W2_ByRowType:	.byte $64, $64, $8F, $82, $84
W2_ByRowType_S2:	.byte $4E, $65, $84, $82, $8A, $A8
W2_ByRowType_S3:
W2_ByRowType_S4:
W2_ByScrCol:	.byte $04, $08, $04, $06, $0A
W2_ByScrCol_S2:	.byte $12, $12, $10, $18, $1C, $14
W2_ByScrCol_S3:
W2_ByScrCol_S4:
W2_ObjSets:	.word W201AO, W202AO, $0002, W2F1AO, W203AO
W2_ObjSets_S2:	.word W2ZROI, W2G1AO, $C42E, $C773, $C3E0, $A8A3
W2_ObjSets_S3:
W2_ObjSets_S4:
W2_LevelLayout:	.word W201AL, W202AL, $0000, W2F1AL, W203AL
W2_LevelLayout_S2:	.word W2ZRO, W2G1AL, $A83F, $AE74, $B0E4, $0800
W2_LevelLayout_S3:
W2_LevelLayout_S4:
