; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
W4_InitIndex:	.byte $00, (W4_ByRowType_S2 - W4_ByRowType), (W4_ByRowType_S3 - W4_ByRowType), (W4_ByRowType_S4 - W4_ByRowType)
W4_ByRowType:	.byte $42, $61, $64, $62, $63, $81, $8C, $82
W4_ByRowType_S2:	.byte $43, $4E, $65, $82, $8A
W4_ByRowType_S3:
W4_ByRowType_S4:
W4_ByScrCol:	.byte $0A, $04, $08, $0C, $0E, $06, $0A, $0E
W4_ByScrCol_S2:	.byte $10, $18, $12, $14, $18
W4_ByScrCol_S3:
W4_ByScrCol_S4:
W4_ObjSets:	.word W4F1AO, W401O, W403O, W4F1AO, W407AO, W402O, IceTestO, W4F2AO
W4_ObjSets_S2:	.word $0002, W4ZROI, W4G1AO, W4F3AO, W4AirshipO
W4_ObjSets_S3:
W4_ObjSets_S4:
W4_LevelLayout:	.word W4F1AL, W401L, W403L, W4F1AL, W407AL, W402L, IceTestL, W4F2AL
W4_LevelLayout_S2:	.word $0000, W2ZRO, W4G1AL, W4F3AL, W4AirshipL
W4_LevelLayout_S3:
W4_LevelLayout_S4:
