; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
W1_InitIndex:	.byte $00, (W1_ByRowType_S2 - W1_ByRowType), (W1_ByRowType_S3 - W1_ByRowType), (W1_ByRowType_S4 - W1_ByRowType)
W1_ByRowType:	.byte $41, $41, $61, $65, $6F, $84, $81, $82, $82
W1_ByRowType_S2:	.byte $61, $61, $60, $62, $84
W1_ByRowType_S3:
W1_ByRowType_S4:
W1_ByScrCol:	.byte $04, $06, $06, $0C, $0E, $06, $08, $0A, $0E
W1_ByScrCol_S2:	.byte $10, $12, $15, $18, $16
W1_ByScrCol_S3:
W1_ByScrCol_S4:
W1_ObjSets:	.word W101AO, W102AO, W102AO, $C5B5, $0002, W103O, $C14D, W1FO, $C2EA
W1_ObjSets_S2:	.word $A582, $A6FF, $0000, $A8E3, $006F
W1_ObjSets_S3:
W1_ObjSets_S4:
W1_LevelLayout:	.word W101AL, W102AL, W102AL, $006F, $BBBF, W103L, $AB3B, W1FL, $0500
W1_LevelLayout_S2:	.word $0B0B, $6464, $0000, $848F, $4E84
W1_LevelLayout_S3:
W1_LevelLayout_S4:
