; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
W3_InitIndex:	.byte $00, (W3_ByRowType_S2 - W3_ByRowType), (W3_ByRowType_S3 - W3_ByRowType), (W3_ByRowType_S4 - W3_ByRowType)
W3_ByRowType:	.byte $4E, $6F, $62, $62, $81, $84, $A1, $A1
W3_ByRowType_S2:	.byte $65, $6A
W3_ByRowType_S3:
W3_ByRowType_S4:
W3_ByScrCol:	.byte $08, $04, $0C, $0E, $06, $0A, $04, $0C
W3_ByScrCol_S2:	.byte $12, $16
W3_ByScrCol_S3:
W3_ByScrCol_S4:
W3_ObjSets:	.word $0002, $C9EB, W3F1AO, $DDC9, W302AO, W303O, W301O, $C799
W3_ObjSets_S2:	.word $B198, $0000
W3_ObjSets_S3:
W3_ObjSets_S4:
W3_LevelLayout:	.word $0000, $AD78, W3F1AL, $B8B2, W302AL, W303L, W301L, $AF88
W3_LevelLayout_S2:	.word $0800, $0800
W3_LevelLayout_S3:
W3_LevelLayout_S4:
