; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!

	.byte $43, $D7, $D7, $BB, $D7, $D7, $D7, $43, $BB, $D7, $BB, $D7, $BB, $D7, $43, $D7
	.byte $D7, $BB, $D7, $D7, $BD, $43, $BB, $D7, $D7, $43, $D7, $D7, $D7, $BD, $D7, $43
	.byte $D7, $D7, $BB, $43, $D7, $D7, $BB, $BB, $BD, $D7, $43, $D7, $BB, $D7, $BB, $C0
	.byte $D7, $D7, $D7, $D7, $BB, $43, $D7, $43, $D7, $BB, $D7, $BB, $D7, $D7, $43, $D7
	.byte $BB, $D7, $E5, $45, $03, $6B, $47, $45, $04, $6B, $47, $D7, $BD, $BB, $D7, $D7
	.byte $D7, $43, $D7, $43, $43, $D7, $D7, $BB, $D7, $43, $46, $43, $BB, $BD, $D7, $BB
	.byte $BB, $D7, $BD, $D7, $BB, $D7, $6A, $45, $47, $6B, $05, $D7, $D7, $D7, $43, $43
	.byte $D7, $43, $D7, $BB, $D7, $43, $D7, $43, $BB, $D7, $D7, $D7, $BB, $D7, $BB, $D7
	.byte $D7, $43, $BB, $D7, $43, $D7, $BB, $BD, $D7, $43, $BB, $D7, $D7, $43, $D7, $D7

	.byte $D7, $C0, $D7, $D7, $43, $D7, $D7, $D7, $D7, $43, $D7, $D7, $D7, $D7, $D7, $D7
	.byte $D7, $D7, $D7, $43, $D7, $D7, $C0, $D7, $D7, $D7, $D7, $D7, $D7, $D7, $D7, $D7
	.byte $43, $D7, $BC, $D7, $D7, $D7, $D7, $D7, $D7, $43, $C0, $43, $D7, $C0, $D7, $D7
	.byte $D7, $D7, $6E, $D7, $43, $D7, $43, $D7, $D7, $D7, $D7, $D7, $43, $D7, $D7, $D7
	.byte $44, $45, $65, $6B, $47, $45, $47, $43, $C0, $D7, $D7, $D7, $D7, $D7, $D7, $D7
	.byte $6C, $43, $D7, $D7, $D7, $C0, $46, $D7, $D7, $D7, $43, $D7, $D7, $D7, $D7, $D7
	.byte $06, $6B, $47, $43, $D7, $43, $48, $45, $6A, $6B, $47, $45, $5E, $D7, $D7, $D7
	.byte $C0, $D7, $46, $D7, $BB, $C0, $46, $D7, $D7, $43, $D7, $43, $D7, $D7, $C0, $D7
	.byte $D7, $D7, $48, $45, $07, $6B, $4A, $43, $D7, $D7, $D7, $D7, $D7, $D7, $D7, $D7

	.byte $FF
