; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
W8_InitIndex:	.byte $00, (W8_ByRowType_S2 - W8_ByRowType), (W8_ByRowType_S3 - W8_ByRowType), (W8_ByRowType_S4 - W8_ByRowType)
W8_ByRowType:	.byte $53, $52, $54, $51, $7F, $7E, $77, $79, $7E
W8_ByRowType_S2:
W8_ByRowType_S3:
W8_ByRowType_S4:
W8_ByScrCol:	.byte $04, $06, $08, $0A, $06, $08, $0A, $0C, $0E
W8_ByScrCol_S2:
W8_ByScrCol_S3:
W8_ByScrCol_S4:
W8_ObjSets:	.word $A594, $AABD, $BA24, $B54F, W8BCastlCO, $BD4D, $B737, W805O, W8ZROI
W8_ObjSets_S2:
W8_ObjSets_S3:
W8_ObjSets_S4:
W8_LevelLayout:	.word $A594, $AABD, $BA24, $B54F, W8BCastlCL, $BD4D, $B737, W805L, W2ZRO
W8_LevelLayout_S2:
W8_LevelLayout_S3:
W8_LevelLayout_S4:
