; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.word W102BL	; Alternate level layout
	.word W102BO	; Alternate object layout
	.byte LEVEL1_SIZE_15 | LEVEL1_YSTART_170
	.byte LEVEL2_BGPAL_00 | LEVEL2_OBJPAL_08 | LEVEL2_XSTART_18
	.byte LEVEL3_TILESET_01 | LEVEL3_VSCROLL_LOCKED | LEVEL3_PIPENOTEXIT
	.byte LEVEL4_BGBANK_INDEX(13) | LEVEL4_INITACT_NOTHING
	.byte LEVEL5_BGM_OVERWORLD | LEVEL5_TIME_300

	.byte $08, $E7, $02, $06, $C6, $02, $07, $D5, $02, $03, $D0, $02, $01, $D2, $02, $03
	.byte $D8, $02, $07, $C9, $02, $03, $C8, $02, $07, $CF, $02, $07, $BF, $02, $07, $C1
	.byte $02, $06, $37, $02, $01, $35, $02, $01, $37, $02, $07, $31, $02, $04, $2B, $02
	.byte $05, $27, $02, $00, $2E, $02, $00, $32, $02, $00, $2C, $02, $07, $1A, $02, $04
	.byte $19, $02, $07, $14, $02, $03, $12, $02, $01, $12, $02, $08, $0E, $02, $06, $08
	.byte $02, $04, $08, $02, $07, $00, $02, $06, $00, $02, $E1, $08, $45, $2B, $00, $43
	.byte $2B, $05, $44, $27, $0C, $42, $2B, $11, $44, $27, $19, $47, $23, $15, $43, $2A
	.byte $06, $82, $26, $0C, $82, $2A, $12, $82, $22, $16, $81, $26, $1A, $85, $4B, $27
	.byte $B1, $18, $2A, $28, $48, $29, $29, $47, $28, $2A, $46, $27, $2B, $45, $26, $2C
	.byte $44, $25, $2D, $43, $24, $2E, $42, $23, $2F, $41, $22, $30, $4B, $03, $31, $02
	.byte $40, $3E, $BA, $01, $28, $36, $92, $E3, $61, $F6, $2B, $C0, $43, $2B, $C5, $44
	.byte $27, $CC, $42, $2B, $D1, $44, $23, $D5, $43, $27, $D9, $47, $2A, $C6, $82, $26
	.byte $CC, $82, $22, $D6, $81, $2A, $D2, $82, $26, $DA, $85, $08, $DB, $02, $4B, $E7
	.byte $B2, $08, $28, $EB, $92, $EE, $61, $F6, $FF